//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.ParkingManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://parkingmanager.com", ConfigurationName="ParkingManagerService.ParkingAppManager")]
    public interface ParkingAppManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="add_sample_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void addData();
        
        // CODEGEN: Параметр "ownerId" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="deleteOwner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        $safeprojectname$.ParkingManagerService.deleteOwnerResponse deleteOwner($safeprojectname$.ParkingManagerService.deleteOwner request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="load_all_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        $safeprojectname$.ParkingManagerService.loadAllDataResponse loadAllData($safeprojectname$.ParkingManagerService.loadAllData request);
        
        // CODEGEN: Параметр "addNewGarageOutput" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="add_new_garage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addNewGarageOutput")]
        $safeprojectname$.ParkingManagerService.addNewGarageResponse addNewGarage($safeprojectname$.ParkingManagerService.addNewGarage request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="add_new_car_to_garage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        $safeprojectname$.ParkingManagerService.addNewCarResponse addNewCar($safeprojectname$.ParkingManagerService.addNewCar request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="update_owner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        $safeprojectname$.ParkingManagerService.updateOwnerResponse updateOwner($safeprojectname$.ParkingManagerService.updateOwner request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="update_car", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        $safeprojectname$.ParkingManagerService.updateCarResponse updateCar($safeprojectname$.ParkingManagerService.updateCar request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="update_garage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        $safeprojectname$.ParkingManagerService.updateGarageResponse updateGarage($safeprojectname$.ParkingManagerService.updateGarage request);
        
        // CODEGEN: Параметр "garageId" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="deleteGarage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        $safeprojectname$.ParkingManagerService.deleteGarageResponse deleteGarage($safeprojectname$.ParkingManagerService.deleteGarage request);
        
        // CODEGEN: Параметр "Car" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="load_car", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Car")]
        $safeprojectname$.ParkingManagerService.loadCarResponse loadCar($safeprojectname$.ParkingManagerService.loadCar request);
        
        // CODEGEN: Параметр "Owner" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="load_owner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Owner")]
        $safeprojectname$.ParkingManagerService.loadOwnerResponse loadOwner($safeprojectname$.ParkingManagerService.loadOwner request);
        
        // CODEGEN: Параметр "Garage" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="load_garage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Garage")]
        $safeprojectname$.ParkingManagerService.loadGarageResponse loadGarage($safeprojectname$.ParkingManagerService.loadGarage request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="add_new_owner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        $safeprojectname$.ParkingManagerService.addNewOwnerResponse addNewOwner($safeprojectname$.ParkingManagerService.addNewOwner request);
        
        // CODEGEN: Параметр "carId" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="delete_car", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        $safeprojectname$.ParkingManagerService.deleteCarResponse deleteCar($safeprojectname$.ParkingManagerService.deleteCar request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteOwner", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class deleteOwner {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ownerId;
        
        public deleteOwner() {
        }
        
        public deleteOwner(int ownerId) {
            this.ownerId = ownerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteOwnerResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class deleteOwnerResponse {
        
        public deleteOwnerResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://parkingmanager.com")]
    public partial class garage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int building_numberField;
        
        private car[] carsField;
        
        private string cityField;
        
        private int idField;
        
        private string streetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int building_number {
            get {
                return this.building_numberField;
            }
            set {
                this.building_numberField = value;
                this.RaisePropertyChanged("building_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cars", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public car[] cars {
            get {
                return this.carsField;
            }
            set {
                this.carsField = value;
                this.RaisePropertyChanged("cars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://parkingmanager.com")]
    public partial class car : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brandField;
        
        private string colorField;
        
        private int idField;
        
        private string modelField;
        
        private owner ownerField;
        
        private string plate_numberField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public owner owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string plate_number {
            get {
                return this.plate_numberField;
            }
            set {
                this.plate_numberField = value;
                this.RaisePropertyChanged("plate_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://parkingmanager.com")]
    public partial class owner : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string surnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadAllData", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadAllData {
        
        public loadAllData() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadAllDataResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadAllDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public $safeprojectname$.ParkingManagerService.garage[] @return;
        
        public loadAllDataResponse() {
        }
        
        public loadAllDataResponse($safeprojectname$.ParkingManagerService.garage[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewGarage", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class addNewGarage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int buildingNumber;
        
        public addNewGarage() {
        }
        
        public addNewGarage(string city, string street, int buildingNumber) {
            this.city = city;
            this.street = street;
            this.buildingNumber = buildingNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewGarageResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class addNewGarageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool addNewGarageOutput;
        
        public addNewGarageResponse() {
        }
        
        public addNewGarageResponse(bool addNewGarageOutput) {
            this.addNewGarageOutput = addNewGarageOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewCar", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class addNewCar {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int garageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string color;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plateNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ownerId;
        
        public addNewCar() {
        }
        
        public addNewCar(int garageId, string brand, string model, int year, string color, string plateNumber, int ownerId) {
            this.garageId = garageId;
            this.brand = brand;
            this.model = model;
            this.year = year;
            this.color = color;
            this.plateNumber = plateNumber;
            this.ownerId = ownerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewCarResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class addNewCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addNewCarResponse() {
        }
        
        public addNewCarResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOwner", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class updateOwner {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ownerID;
        
        public updateOwner() {
        }
        
        public updateOwner(string field, string newData, int ownerID) {
            this.field = field;
            this.newData = newData;
            this.ownerID = ownerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOwnerResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class updateOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateOwnerResponse() {
        }
        
        public updateOwnerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCar", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class updateCar {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int carID;
        
        public updateCar() {
        }
        
        public updateCar(string field, string newData, int carID) {
            this.field = field;
            this.newData = newData;
            this.carID = carID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCarResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class updateCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateCarResponse() {
        }
        
        public updateCarResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateGarage", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class updateGarage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int garageId;
        
        public updateGarage() {
        }
        
        public updateGarage(string field, string newData, int garageId) {
            this.field = field;
            this.newData = newData;
            this.garageId = garageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateGarageResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class updateGarageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateGarageResponse() {
        }
        
        public updateGarageResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteGarage", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class deleteGarage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int garageId;
        
        public deleteGarage() {
        }
        
        public deleteGarage(int garageId) {
            this.garageId = garageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteGarageResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class deleteGarageResponse {
        
        public deleteGarageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadCar", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadCar {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int carId;
        
        public loadCar() {
        }
        
        public loadCar(int carId) {
            this.carId = carId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadCarResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public $safeprojectname$.ParkingManagerService.car Car;
        
        public loadCarResponse() {
        }
        
        public loadCarResponse($safeprojectname$.ParkingManagerService.car Car) {
            this.Car = Car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadOwner", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadOwner {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ownerId;
        
        public loadOwner() {
        }
        
        public loadOwner(int ownerId) {
            this.ownerId = ownerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadOwnerResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public $safeprojectname$.ParkingManagerService.owner Owner;
        
        public loadOwnerResponse() {
        }
        
        public loadOwnerResponse($safeprojectname$.ParkingManagerService.owner Owner) {
            this.Owner = Owner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadGarage", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadGarage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int garageId;
        
        public loadGarage() {
        }
        
        public loadGarage(int garageId) {
            this.garageId = garageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadGarageResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class loadGarageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public $safeprojectname$.ParkingManagerService.garage Garage;
        
        public loadGarageResponse() {
        }
        
        public loadGarageResponse($safeprojectname$.ParkingManagerService.garage Garage) {
            this.Garage = Garage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewOwner", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class addNewOwner {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string surname;
        
        public addNewOwner() {
        }
        
        public addNewOwner(string name, string surname) {
            this.name = name;
            this.surname = surname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewOwnerResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class addNewOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addNewOwnerResponse() {
        }
        
        public addNewOwnerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCar", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class deleteCar {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://parkingmanager.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int carId;
        
        public deleteCar() {
        }
        
        public deleteCar(int carId) {
            this.carId = carId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCarResponse", WrapperNamespace="http://parkingmanager.com", IsWrapped=true)]
    public partial class deleteCarResponse {
        
        public deleteCarResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParkingAppManagerChannel : $safeprojectname$.ParkingManagerService.ParkingAppManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParkingAppManagerClient : System.ServiceModel.ClientBase<$safeprojectname$.ParkingManagerService.ParkingAppManager>, $safeprojectname$.ParkingManagerService.ParkingAppManager {
        
        public ParkingAppManagerClient() {
        }
        
        public ParkingAppManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParkingAppManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkingAppManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkingAppManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addData() {
            base.Channel.addData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.deleteOwnerResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.deleteOwner($safeprojectname$.ParkingManagerService.deleteOwner request) {
            return base.Channel.deleteOwner(request);
        }
        
        public void deleteOwner(int ownerId) {
            $safeprojectname$.ParkingManagerService.deleteOwner inValue = new $safeprojectname$.ParkingManagerService.deleteOwner();
            inValue.ownerId = ownerId;
            $safeprojectname$.ParkingManagerService.deleteOwnerResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).deleteOwner(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.loadAllDataResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.loadAllData($safeprojectname$.ParkingManagerService.loadAllData request) {
            return base.Channel.loadAllData(request);
        }
        
        public $safeprojectname$.ParkingManagerService.garage[] loadAllData() {
            $safeprojectname$.ParkingManagerService.loadAllData inValue = new $safeprojectname$.ParkingManagerService.loadAllData();
            $safeprojectname$.ParkingManagerService.loadAllDataResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).loadAllData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.addNewGarageResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.addNewGarage($safeprojectname$.ParkingManagerService.addNewGarage request) {
            return base.Channel.addNewGarage(request);
        }
        
        public bool addNewGarage(string city, string street, int buildingNumber) {
            $safeprojectname$.ParkingManagerService.addNewGarage inValue = new $safeprojectname$.ParkingManagerService.addNewGarage();
            inValue.city = city;
            inValue.street = street;
            inValue.buildingNumber = buildingNumber;
            $safeprojectname$.ParkingManagerService.addNewGarageResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).addNewGarage(inValue);
            return retVal.addNewGarageOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.addNewCarResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.addNewCar($safeprojectname$.ParkingManagerService.addNewCar request) {
            return base.Channel.addNewCar(request);
        }
        
        public bool addNewCar(int garageId, string brand, string model, int year, string color, string plateNumber, int ownerId) {
            $safeprojectname$.ParkingManagerService.addNewCar inValue = new $safeprojectname$.ParkingManagerService.addNewCar();
            inValue.garageId = garageId;
            inValue.brand = brand;
            inValue.model = model;
            inValue.year = year;
            inValue.color = color;
            inValue.plateNumber = plateNumber;
            inValue.ownerId = ownerId;
            $safeprojectname$.ParkingManagerService.addNewCarResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).addNewCar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.updateOwnerResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.updateOwner($safeprojectname$.ParkingManagerService.updateOwner request) {
            return base.Channel.updateOwner(request);
        }
        
        public bool updateOwner(string field, string newData, int ownerID) {
            $safeprojectname$.ParkingManagerService.updateOwner inValue = new $safeprojectname$.ParkingManagerService.updateOwner();
            inValue.field = field;
            inValue.newData = newData;
            inValue.ownerID = ownerID;
            $safeprojectname$.ParkingManagerService.updateOwnerResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).updateOwner(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.updateCarResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.updateCar($safeprojectname$.ParkingManagerService.updateCar request) {
            return base.Channel.updateCar(request);
        }
        
        public bool updateCar(string field, string newData, int carID) {
            $safeprojectname$.ParkingManagerService.updateCar inValue = new $safeprojectname$.ParkingManagerService.updateCar();
            inValue.field = field;
            inValue.newData = newData;
            inValue.carID = carID;
            $safeprojectname$.ParkingManagerService.updateCarResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).updateCar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.updateGarageResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.updateGarage($safeprojectname$.ParkingManagerService.updateGarage request) {
            return base.Channel.updateGarage(request);
        }
        
        public bool updateGarage(string field, string newData, int garageId) {
            $safeprojectname$.ParkingManagerService.updateGarage inValue = new $safeprojectname$.ParkingManagerService.updateGarage();
            inValue.field = field;
            inValue.newData = newData;
            inValue.garageId = garageId;
            $safeprojectname$.ParkingManagerService.updateGarageResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).updateGarage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.deleteGarageResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.deleteGarage($safeprojectname$.ParkingManagerService.deleteGarage request) {
            return base.Channel.deleteGarage(request);
        }
        
        public void deleteGarage(int garageId) {
            $safeprojectname$.ParkingManagerService.deleteGarage inValue = new $safeprojectname$.ParkingManagerService.deleteGarage();
            inValue.garageId = garageId;
            $safeprojectname$.ParkingManagerService.deleteGarageResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).deleteGarage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.loadCarResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.loadCar($safeprojectname$.ParkingManagerService.loadCar request) {
            return base.Channel.loadCar(request);
        }
        
        public $safeprojectname$.ParkingManagerService.car loadCar(int carId) {
            $safeprojectname$.ParkingManagerService.loadCar inValue = new $safeprojectname$.ParkingManagerService.loadCar();
            inValue.carId = carId;
            $safeprojectname$.ParkingManagerService.loadCarResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).loadCar(inValue);
            return retVal.Car;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.loadOwnerResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.loadOwner($safeprojectname$.ParkingManagerService.loadOwner request) {
            return base.Channel.loadOwner(request);
        }
        
        public $safeprojectname$.ParkingManagerService.owner loadOwner(int ownerId) {
            $safeprojectname$.ParkingManagerService.loadOwner inValue = new $safeprojectname$.ParkingManagerService.loadOwner();
            inValue.ownerId = ownerId;
            $safeprojectname$.ParkingManagerService.loadOwnerResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).loadOwner(inValue);
            return retVal.Owner;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.loadGarageResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.loadGarage($safeprojectname$.ParkingManagerService.loadGarage request) {
            return base.Channel.loadGarage(request);
        }
        
        public $safeprojectname$.ParkingManagerService.garage loadGarage(int garageId) {
            $safeprojectname$.ParkingManagerService.loadGarage inValue = new $safeprojectname$.ParkingManagerService.loadGarage();
            inValue.garageId = garageId;
            $safeprojectname$.ParkingManagerService.loadGarageResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).loadGarage(inValue);
            return retVal.Garage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.addNewOwnerResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.addNewOwner($safeprojectname$.ParkingManagerService.addNewOwner request) {
            return base.Channel.addNewOwner(request);
        }
        
        public bool addNewOwner(string name, string surname) {
            $safeprojectname$.ParkingManagerService.addNewOwner inValue = new $safeprojectname$.ParkingManagerService.addNewOwner();
            inValue.name = name;
            inValue.surname = surname;
            $safeprojectname$.ParkingManagerService.addNewOwnerResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).addNewOwner(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ParkingManagerService.deleteCarResponse $safeprojectname$.ParkingManagerService.ParkingAppManager.deleteCar($safeprojectname$.ParkingManagerService.deleteCar request) {
            return base.Channel.deleteCar(request);
        }
        
        public void deleteCar(int carId) {
            $safeprojectname$.ParkingManagerService.deleteCar inValue = new $safeprojectname$.ParkingManagerService.deleteCar();
            inValue.carId = carId;
            $safeprojectname$.ParkingManagerService.deleteCarResponse retVal = (($safeprojectname$.ParkingManagerService.ParkingAppManager)(this)).deleteCar(inValue);
        }
    }
}
